// Code generated by "stringer -type Backlight -trimprefix=Backlight"; DO NOT EDIT.

package smclcd

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BacklightOff-0]
	_ = x[BacklightOn-1]
}

const _Backlight_name = "OffOn"

var _Backlight_index = [...]uint8{0, 3, 5}

func (i Backlight) String() string {
	if i >= Backlight(len(_Backlight_index)-1) {
		return "Backlight(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Backlight_name[_Backlight_index[i]:_Backlight_index[i+1]]
}
