// Code generated by "stringer -type Cursor -trimprefix=Cursor"; DO NOT EDIT.

package smclcd

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CursorOff-0]
	_ = x[CursorBlock-1]
	_ = x[CursorUnderline-2]
	_ = x[CursorBoth-3]
}

const _Cursor_name = "OffBlockUnderlineBoth"

var _Cursor_index = [...]uint8{0, 3, 8, 17, 21}

func (i Cursor) String() string {
	if i >= Cursor(len(_Cursor_index)-1) {
		return "Cursor(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Cursor_name[_Cursor_index[i]:_Cursor_index[i+1]]
}
