// Code generated by "stringer -type KeyEvent -trimprefix=Key"; DO NOT EDIT.

package smclcd

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KeyRelease-0]
	_ = x[KeyPress-1]
}

const _KeyEvent_name = "ReleasePress"

var _KeyEvent_index = [...]uint8{0, 7, 12}

func (i KeyEvent) String() string {
	if i >= KeyEvent(len(_KeyEvent_index)-1) {
		return "KeyEvent(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _KeyEvent_name[_KeyEvent_index[i]:_KeyEvent_index[i+1]]
}
