// Code generated by "doxxer . help -all"; DO NOT EDIT.

/*
TODO.

Usage:

	smclcd [global flags] <command> [arguments...]

Global Flags:

	-V	TODO
	-debug
	  	TODO
	-path string
	  	TODO
	-serial string
	  	TODO

Commands:

	backlight     Backlight control
	clear         Clear display
	cursor        Cursor control
	home          Move cursor to home position
	input         Print input events
	list          List compatible displays
	read          Read from display
	version       Print display version
	watch         Write periodic command output to display
	write         Write to display

Use "smclcd help <command>" for more information about that command.
Report issues to https://github.com/sstallion/go-smclcd/issues.

# Backlight control

TODO.

Usage:

	smclcd [global flags] backlight <state>

Use "smclcd help" for more information about global flags.

# Clear display

TODO.

Usage:

	smclcd [global flags] clear

Use "smclcd help" for more information about global flags.

# Cursor control

TODO.

Usage:

	smclcd [global flags] cursor <state>

Use "smclcd help" for more information about global flags.

# Move cursor to home position

TODO.

Usage:

	smclcd [global flags] home

Use "smclcd help" for more information about global flags.

# Print input events

TODO.

Usage:

	smclcd [global flags] input

Use "smclcd help" for more information about global flags.

# List compatible displays

TODO.

Usage:

	smclcd [global flags] list

Use "smclcd help" for more information about global flags.

# Read from display

TODO.

Usage:

	smclcd [global flags] read [-n count] [-x col] [-y line]

Flags:

	-n count
	  	count
	-x col
	  	col
	-y line
	  	line

Use "smclcd help" for more information about global flags.

# Print display version

TODO.

Usage:

	smclcd [global flags] version

Use "smclcd help" for more information about global flags.

# Write periodic command output to display

TODO.

Usage:

	smclcd [global flags] watch [flags] <command> [arguments...]

Flags:

	-backlight state
	  	state
	-n interval
	  	interval (default 30s)

Use "smclcd help" for more information about global flags.

# Write to display

TODO.

Usage:

	smclcd [global flags] write [-x col] [-y line] arguments...

Flags:

	-clear
	  	TODO
	-x col
	  	col
	-y line
	  	line

Use "smclcd help" for more information about global flags.
*/
package main
